highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Sourav Anand's Resume
name: Sourav Anand
email: mail@souravanand.com
email_full: mailto:mail@souravanand.com
website: souravanand.com
website_full: http://souravanand.com/
github: souravan
#twitter: twitter
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://www.google.com/maps/place/Indian+Institute+of+Technology+Kanpur/'
#address: IIT Kanpur
postcode: IIT Kanpur
city: Kanpur
country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
